name: auth
description: A new Flutter package.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../../libraries/dependencies
  home:
    path: ../../features/home

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

flutter: